apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}-grafana-query
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
    grafana_dashboard: "1"
data:
  {{- (.Files.Glob "files/thanos-query.json").AsConfig | nindent 2 }}

