{{- if .Values.compact.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-compact
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: compact
spec:
  groups:
  - name: thanos-compact.rules
    rules:
    - alert: ThanosCompactHalted
      expr: thanos_compactor_halted{app="thanos-compact"} == 1
      for: 5m
      annotations:
        summary: Thanos compaction has failed to run and now is halted
        impact: Long term storage queries will be slower
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosCompactCompactionsFailed
      expr: rate(prometheus_tsdb_compactions_failed_total{app="thanos-compact"}[5m]) > 0
      annotations:
        summary: Thanos Compact is failing compaction
        impact: Long term storage queries will be slower
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosCompactBucketOperationsFailed
      expr: rate(thanos_objstore_bucket_operation_failures_total{app="thanos-compact"}[5m]) > 0
      annotations:
        summary: Thanos Compact bucket operations are failing
        impact: Long term storage queries will be slower
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosCompactNotRunIn24Hours
      expr: (time() - max(thanos_objstore_bucket_last_successful_upload_time{app="thanos-compact"}) ) /60/60 > 24
      annotations:
        summary: Thanos Compaction has not been run in 24 hours
        impact: Long term storage queries will be slower
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosComactionIsNotRunning
      expr: up{app="thanos-compact"} == 0 or absent({app="thanos-compact"})
      for: 5m
      annotations:
        summary: Thanos Compaction is not running
        impact: Long term storage queries will be slower
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
    - alert: ThanosComactionMultipleCompactionsAreRunning
      expr: sum(up{app="thanos-compact"}) > 1
      for: 5m
      annotations:
        summary: Multiple replicas of Thanos compaction shouldn't be running.
        impact: Metrics in long term storage may be corrupted
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
{{- end -}}
