apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-object-store
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  store.yaml: {{ .Values.objectStore | b64enc }}
