{{- if .Values.query.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-query
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
spec:
  groups:
  - name: thanos-query.rules
    rules:
    - alert: ThanosQueryIsNotRunning
      expr: up{job="thanos-query-http"} == 0 or absent({job="thanos-query-http"})
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Thanos Query is not running
    - alert: ThanosQueryGrpcErrorRate
      expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",job="thanos-query-http"}[5m]) > 0
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Thanos Query is returning Internal/Unavailable errors
        description: Grafana is not showing metrics
{{- end -}}
