{{- if .Values.query.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-query
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
spec:
  groups:
  - name: thanos-query.rules
    rules:
    - alert: ThanosQueryGrpcErrorRate
      expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",name="prometheus"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Query is returning Internal/Unavailable errors
        impact: Grafana is not showing metrics
        action: Check {{`{{ $labels.kubernetes_pod_name }}`}} pod logs in {{`{{ $labels.kubernetes_namespace}}`}} namespace
{{- end -}}
