{{- if .Values.compact.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-compact
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: compact
spec:
  groups:
  - name: thanos-compact.rules
    rules:
    - alert: ThanosCompactHalted
      expr: thanos_compactor_halted{job="thanos-compact-http"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Thanos Compact has failed to run and now is halted
        description: Long term storage queries will be slower
    - alert: ThanosCompactCompactsFailed
      expr: rate(prometheus_tsdb_Compacts_failed_total{job="thanos-compact-http"}[5m]) > 0
      labels:
        severity: warning
      annotations:
        summary: Thanos Compact is failing Compact
        description: Long term storage queries will be slower
    - alert: ThanosCompactBucketOperationsFailed
      expr: sum without (operation) (rate(thanos_objstore_bucket_operation_failures_total{job="thanos-compact-http"}[5m])) > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Thanos Compact bucket operations are failing
    - alert: ThanosCompactNotRunIn24Hours
      expr: max(thanos_objstore_bucket_last_successful_upload_time{job="thanos-compact-http"}) != 0 and
              (time() - max(thanos_objstore_bucket_last_successful_upload_time{job="thanos-compact-http"}) ) /60/60 > 24
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Thanos Compact has not been run in 24 hours
        description: Long term storage queries will be slower
    - alert: ThanosComactionIsNotRunning
      expr: up{job="thanos-compact-http"} == 0 or absent({job="thanos-compact-http"})
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Thanos Compact is not running
        description: Long term storage queries will be slower
    - alert: ThanosComactionMultipleCompactsAreRunning
      expr: sum(up{job="thanos-compact-http"}) > 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Multiple replicas of Thanos Compact shouldn't be running.
        description: Metrics in long term storage may be corrupted
{{- end -}}
