{{- if .Values.query.enabled }}
{{- if .Values.query.grpcIngress.host }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.fullname" . }}-query
{{- if .Values.query.grpcIngress.annotations }}
  annotations:
{{ toYaml .Values.query.grpcIngress.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
spec:
  rules:
  - host: {{ .Values.query.grpcIngress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "thanos.fullname" . }}-query-grpc
          servicePort: 10901
{{- end -}}
{{- end -}}
