{{- if .Values.query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-query
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
spec:
  replicas: {{ .Values.query.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thanos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: query
  template:
    metadata:
    {{- if .Values.query.deployment.annotations }}
      annotations:
{{ toYaml .Values.query.deployment.annotations | indent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "thanos.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: query
    spec:
      containers:
        - name: thanos-query
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "query"
            - "--log.level={{ .Values.query.logLevel }}"
            - "--query.auto-downsampling"
            {{- if .Values.query.storeDNSResolver }}
            - "--store.sd-dns-resolver={{ .Values.query.storeDNSResolver }}"
            {{- end }}
            {{- range .Values.query.stores }}
            - "--store={{ . }}"
            {{- end }}
            - "--query.replica-label={{ .Values.query.queryReplicaLabel }}"
            {{- if .Values.query.secure }}
            - "--grpc-client-tls-secure"
            {{- end }}
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          resources:
{{ toYaml .Values.query.resources | indent 12 }}
    {{- with .Values.query.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.query.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.query.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
