{{- if .Values.rule.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}-rule
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: rule
data:
  rule.rules.yaml: |
    {{- toYaml .Values.rule.rules | default "{}" | nindent 4 }}
{{- end -}}
