apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-sidecar-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sidecar
spec:
  ports:
    - port: 10902
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prometheus
    # XXX: why prometheus operator cuts at 26?
    prometheus: "{{- printf "%s-prometheus-operator" .Release.Name | trunc 26 | trimSuffix "-" -}}-prometheus"
  type: {{ .Values.sidecar.httpService.type }}
  {{- if .Values.sidecar.httpService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.sidecar.httpService.externalTrafficPolicy }}
  {{- end }}
