{{- $fullname := include "thanos.fullname" . }}
{{- $name := include "thanos.name" . }}
{{- $chart := include "thanos.chart" . }}
{{- $releaseName := .Release.Name }}
{{- $service := .Release.Service }}
{{- $prometheus := printf "%s-prometheus-operator" .Release.Name | trunc 26 | trimSuffix "-" }}

{{- if and .Values.sidecar.ingress.basename .Values.sidecar.ingress.domain }}

{{- $count := (index .Values "prometheus-operator" "prometheus" "prometheusSpec" "replicas" | int) }}
{{- range $replica := until $count }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-sidecar-grpc-{{ $replica }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $service }}
    app.kubernetes.io/component: sidecar
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 10901
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: prometheus
    statefulset.kubernetes.io/pod-name: "prometheus-{{ $prometheus }}-prometheus-{{ $replica }}"
{{- end }}

{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-sidecar-grpc
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $service }}
    app.kubernetes.io/component: sidecar
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 10901
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: prometheus
    prometheus: "{{ $prometheus }}-prometheus"
{{- end }}
