apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-sidecar
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sidecar
spec:
  groups:
  - name: thanos-sidecar.rules
    rules:
    - alert: ThanosSidecarPrometheusDown
      expr: thanos_sidecar_prometheus_up{job="thanos-sidecar-http"} == 0 or absent({job="thanos-sidecar-http"})
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Thanos Sidecar cannot connect to Prometheus
        description: Prometheus configuration is not being refreshed
    - alert: ThanosSidecarBucketOperationsFailed
      expr: sum without (operation) (rate(thanos_objstore_bucket_operation_failures_total{job="thanos-sidecar-http"}[5m])) > 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Thanos Sidecar bucket operations are failing
        description: We may lose metrics data if this keeps happening
    - alert: ThanosSidecarGrpcErrorRate
      expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",job="thanos-sidecar-http"}[5m]) > 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Thanos Sidecar is returning Internal/Unavailable errors
        description: Prometheus queries are failing
