prometheus-operator:
  prometheus:
    prometheusSpec:
      replicas: 2
      externalLabels:
        region: local
      thanos:
        objectStorageConfig:
          # this should be ${releaseName}-thanos-object-store
          name: thanos-thanos-object-store
          key: store.yaml

  grafana:
    envFromSecret: grafana-secrets
    env:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_USER: grafana
      GF_DATABASE_HOST: grafanadb-mysql.mysql.svc.cluster.local
      # example for github oauth
      # GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: caarlos0-m
      # GF_AUTH_GITHUB_CLIENT_ID: fake
      # GF_AUTH_GITHUB_ENABLED: 'true'
      # GF_AUTH_BASIC_ENABLED: 'false'
      # GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      # GF_AUTH_OAUTH_AUTO_LOGIN: 'true'

query:
  replicas: 2
  logLevel: info

store:
  replicas: 2
